export const GET_PAGINATE_REQUEST = "GET_PAGINATE_REQUEST"
export const GET_PAGINATE_SUCCESS = "GET_PAGINATE_SUCCESS"
export const GET_PAGINATE_FAILURE = "GET_PAGINATE_FAILURE"

export const SEARCH_PAGINATE_REQUEST = "SEARCH_PAGINATE_REQUEST"
export const SEARCH_PAGINATE_SUCCESS = "SEARCH_PAGINATE_SUCCESS"
export const SEARCH_PAGINATE_FAILURE = "SEARCH_PAGINATE_FAILURE"

export const ADD_REQUEST = "ADD_REQUEST"
export const ADD_SUCCESS = "ADD_SUCCESS"
export const ADD_FAILURE = "ADD_FAILURE"

export const DELETE_REQUEST = "DELETE_REQUEST"
export const DELETE_SUCCESS = "DELETE_SUCCESS"
export const DELETE_FAILURE = "DELETE_FAILURE"

export const UPDATE_REQUEST = "UPDATE_REQUEST"
export const UPDATE_SUCCESS = "UPDATE_SUCCESS"
export const UPDATE_FAILURE = "UPDATE_FAILURE"

export const limit = 4

